### PR TITLE
Make cards draggable/movable on screen

### PR DESCRIPTION
**Pull request by gitchrisadams**

### CODE REVIEW

**Comment by abrie** [comment]
Looks like we're missing a bunch of code added by PR #14?

**Comment by gitchrisadams** [comment]
@abrie No, it is there: https://github.com/gitchrisadams/MemberDirectory/commits/cadams_7_27
See commits july 24th and 26, my git log shows those commits in my branch, so we should be good.

**Comment by abrie** [comment]
Oops, my bad.

**Comment by gitchrisadams** [comment]
Look good for merging? If so comment here and I'll merge. @abrie @jordanivy

**Comment by abrie** [comment]
Why are the cards draggable?

**Comment by gitchrisadams** [comment]
@abrie We were thinking of doing some sort of memory game. Interesting display of the technology at the minimum. Also you can reorder them so your not guessing based on order person is in but on person's face maybe.

**Comment by abrie** [comment]
Ok, yeah it is pretty cool. But I'd argue that it shouldn't be included in this PR; because it adds a dependency and complexity without contributing functionality. The other stuff in this PR is great.

**Comment by gitchrisadams** [comment]
@abrie I'll have to look at how we can do random order and if using draggable for that, don't remember off hand, will look into that, we can discuss.

**Comment by gitchrisadams** [comment]
@abrie Removed draggable library. Please comment here if you think we are good to merge.

**Pull request merged**
